//! Triangle meshes, written once. A link's visual, a scanned object: the
//! same file drawn by six arms or set down in six cells is one layer,
//! `<stem>_assets/meshes/<name>.usdc`, and every prim that draws it is a
//! reference to that layer's `/Mesh` with its own transform and colour
//! (design-rl-tabletop.md G6). Binary, because a text mesh is several
//! times the size for nothing a reader wants; the crate version is
//! stamped down like the main layer's so older readers open it.
//!
//! The studio's single-file download asks for the meshes inline instead
//! (`ExportOptions::mesh_layers = false`): the same prims, the triangles
//! authored on them, no sibling files.
use super::*;

pub(super) struct MeshLayers {
    stem: String,
    inline: bool,
    /// Mesh file and scale → the layer written for it.
    written: HashMap<(PathBuf, [u64; 3]), Written>,
    used: HashMap<String, usize>,
    /// Layers this export composed itself, relative to the main layer.
    pub generated: Vec<(PathBuf, Vec<u8>)>,
}

struct Written {
    /// The reference's asset path, relative to the main layer.
    asset: String,
    /// The file painted its faces itself (an `mtllib`), so a prim that
    /// asks for no colour of its own shows those.
    face_colors: bool,
}

impl MeshLayers {
    pub fn new(stem: &str, inline: bool) -> Self {
        MeshLayers {
            stem: stem.into(),
            inline,
            written: HashMap::new(),
            used: HashMap::new(),
            generated: Vec::new(),
        }
    }

    /// Authors `prim` as the mesh at `path` scaled by `scale`, posed at
    /// `pose`, painted `color` — or, without one, the file's own face
    /// colours, else the neutral environment grey. `hint` names the layer
    /// the mesh is written to (a link, an obstacle), uniquified.
    #[allow(clippy::too_many_arguments)]
    pub fn author(
        &mut self,
        layer: &mut LayerBuilder,
        prim: &str,
        hint: &str,
        path: &Path,
        scale: &Vector3<f64>,
        pose: &XformValue,
        color: Option<[f32; 3]>,
    ) -> Result<(), UsdExportError> {
        if self.inline {
            let data = load(path)?;
            layer.ensure_prim(prim, Specifier::Def, Some("Mesh"));
            author_mesh(layer, prim, &data, scale);
            let painted = color.is_none() && author_face_colors(layer, prim, &data);
            layer.xform(prim, pose, None);
            if !painted {
                flat_color(layer, prim, color, false);
            }
            return Ok(());
        }
        let key = (
            path.to_path_buf(),
            [scale.x.to_bits(), scale.y.to_bits(), scale.z.to_bits()],
        );
        if !self.written.contains_key(&key) {
            let data = load(path)?;
            let mut mesh = LayerBuilder::new();
            mesh.root_field(FieldKey::DefaultPrim.as_ref(), Value::Token("Mesh".into()));
            mesh.root_field(
                FieldKey::Documentation.as_ref(),
                Value::String(format!(
                    "Mesh `{}` generated by botrail; referenced by the layer beside it",
                    path.file_name()
                        .map(|f| f.to_string_lossy().to_string())
                        .unwrap_or_default()
                )),
            );
            mesh.root_field("metersPerUnit", Value::Double(1.0));
            mesh.root_field("upAxis", Value::Token("Z".into()));
            mesh.ensure_prim("/Mesh", Specifier::Def, Some("Mesh"));
            author_mesh(&mut mesh, "/Mesh", &data, scale);
            let face_colors = author_face_colors(&mut mesh, "/Mesh", &data);
            let mut bytes = std::io::Cursor::new(Vec::new());
            CrateWriter::write(&mesh.finish(), &mut bytes)
                .map_err(|e| UsdExportError::Author(format!("usdc write: {e}")))?;
            let mut bytes = bytes.into_inner();
            stamp_crate_version(&mut bytes);
            let name = unique_child(&mut self.used, &sanitize_name(hint));
            let rel = format!("{}_assets/meshes/{name}.usdc", self.stem);
            self.generated.push((PathBuf::from(&rel), bytes));
            self.written.insert(
                key.clone(),
                Written {
                    asset: format!("./{rel}"),
                    face_colors,
                },
            );
        }
        let written = &self.written[&key];
        layer.ensure_prim(prim, Specifier::Def, Some("Mesh"));
        layer.prim_field(
            prim,
            FieldKey::References,
            Value::ReferenceListOp(ListOp {
                prepended_items: vec![Reference {
                    asset_path: written.asset.clone(),
                    prim_path: sdf::path("/Mesh")
                        .map_err(|e| UsdExportError::Author(e.to_string()))?,
                    layer_offset: Default::default(),
                    custom_data: HashMap::new(),
                }],
                ..Default::default()
            }),
        );
        layer.xform(prim, pose, None);
        if color.is_some() || !written.face_colors {
            // A flat colour over a face-painted file has to say it is
            // constant: the referenced primvar's `uniform` would otherwise
            // stay composed over one value.
            flat_color(layer, prim, color, written.face_colors);
        }
        Ok(())
    }
}

fn load(path: &Path) -> Result<botrail_mesh::MeshData, UsdExportError> {
    botrail_mesh::load_path(path).map_err(|e| UsdExportError::Mesh {
        path: path.display().to_string(),
        message: e.to_string(),
    })
}

/// The triangles: points (scaled), counts, indices, extent, and no
/// subdivision — a mesh is what the file says, not a limit surface.
fn author_mesh(
    layer: &mut LayerBuilder,
    prim: &str,
    data: &botrail_mesh::MeshData,
    scale: &Vector3<f64>,
) {
    let points: Vec<gf::Vec3f> = data
        .vertices
        .iter()
        .map(|v| {
            gf::vec3f(
                (v[0] * scale.x) as f32,
                (v[1] * scale.y) as f32,
                (v[2] * scale.z) as f32,
            )
        })
        .collect();
    let (mut min, mut max) = ([f32::MAX; 3], [f32::MIN; 3]);
    for p in &points {
        for (k, v) in [p.x, p.y, p.z].into_iter().enumerate() {
            min[k] = min[k].min(v);
            max[k] = max[k].max(v);
        }
    }
    let indices: Vec<i32> = data
        .indices
        .iter()
        .flat_map(|t| t.iter().map(|&i| i as i32))
        .collect();
    let counts = vec![3i32; data.indices.len()];
    layer.attr(
        prim,
        "points",
        "point3f[]",
        AttrValue::Default(Value::Vec3fVec(points)),
    );
    layer.attr(
        prim,
        "faceVertexCounts",
        "int[]",
        AttrValue::Default(Value::IntVec(counts)),
    );
    layer.attr(
        prim,
        "faceVertexIndices",
        "int[]",
        AttrValue::Default(Value::IntVec(indices)),
    );
    layer.attr(
        prim,
        "extent",
        "float3[]",
        AttrValue::Default(Value::Vec3fVec(vec![
            gf::vec3f(min[0], min[1], min[2]),
            gf::vec3f(max[0], max[1], max[2]),
        ])),
    );
    layer.attr(
        prim,
        "subdivisionScheme",
        "token",
        AttrValue::Uniform(Value::Token(tf::Token::from("none"))),
    );
}

/// A mesh that carried its own materials paints per face — the
/// manufacturer's own colouring, one `displayColor` per face. `uniform`
/// is metadata on the primvar, not a sibling property: without it a
/// reader takes the array as `constant` and the whole mesh goes one
/// colour. Returns whether anything was painted.
fn author_face_colors(layer: &mut LayerBuilder, prim: &str, data: &botrail_mesh::MeshData) -> bool {
    if data.face_colors.is_empty() {
        return false;
    }
    let colors: Vec<gf::Vec3f> = data
        .face_colors
        .iter()
        .map(|c| gf::vec3f(c[0], c[1], c[2]))
        .collect();
    layer.attr_meta(
        prim,
        "primvars:displayColor",
        "color3f[]",
        AttrValue::Default(Value::Vec3fVec(colors)),
        &[("interpolation", Value::Token(tf::Token::from("uniform")))],
    );
    true
}

/// One colour for the whole mesh: the scene's choice, or the neutral grey.
fn flat_color(layer: &mut LayerBuilder, prim: &str, color: Option<[f32; 3]>, over_faces: bool) {
    let [r, g, b] = color.unwrap_or(ENV_COLOR);
    let value = AttrValue::Default(Value::Vec3fVec(vec![gf::vec3f(r, g, b)]));
    if over_faces {
        layer.attr_meta(
            prim,
            "primvars:displayColor",
            "color3f[]",
            value,
            &[("interpolation", Value::Token(tf::Token::from("constant")))],
        );
    } else {
        layer.attr(prim, "primvars:displayColor", "color3f[]", value);
    }
}
