"""One source, the whole document set — the cell handed over.

Everything a robot cell is delivered as comes out of the *same* script here:
the layout sheet (SVG for the review, DXF for the 2D CAD the plant uses),
the bill of materials, the I/O list and controller topology, the control
logic as PLCopen XML for the PLC IDE and the interlock table beside it, the
robot program, the baked cycle as USD, the portable project and its Python,
and a cell report that gathers the numbers (cycle time, clearance, I/O
counts, scenario matrix, BOM totals, footprint) with the SHA-256 of every
file it lists. None of these are typed in beside the model — each is *derived* from
the scene, so a layout edit that costs a second, adds a panel or moves a
sensor shows up in the report, the drawing and the list at once, and they
can never disagree with each other or with the simulation that verified
the cell.

The cell is the pick-and-branch cell of `export_urscript.py` (a six-axis
arm, a conveyor, a photo-eye, a spec-gauge branch, a UR controller wearing
the I/O), furnished with a table, a fence and identified parts, so the BOM
and the layout have something to say.

Run with:  python examples/engineering/cell_deliverables_demo.py [out_dir]
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "export"))

import botrail as bt  # noqa: E402
import export_urscript as pick  # noqa: E402

FENCE_PITCH = 1.0  # panel width, m — change it and watch the BOM and the sheet follow


def furnish(scene: bt.Scene, fence_pitch: float = FENCE_PITCH) -> None:
    """Scenery and identity: the controller cabinet and the reject bin, a
    fence around the cell with a door gap on the south side, and what each
    piece of equipment *is* (`set_part`) — the identity the BOM, the layout
    labels and the report are derived from. Nothing here changes the
    cycle."""
    # The control cabinet stands in the corner, ordered from the catalog:
    # the enclosure is an article of its own (body, plinth base, mounting
    # plate — three lines with masses and part numbers), and the UR
    # controller it houses keeps its own line as the `UR` I/O node below.
    # The reject chute is a bin west of the arm.
    bt.parts.cabinet(scene, "cabinet", catalog="nito/fz/standard",
                     size=(0.6, 0.4, 1.6), position=(-0.85, 0.72), base_height=0.1)
    scene.add_box("chute", size=(0.3, 0.3, 0.4), position=(-0.55, 0.05, 0.2))
    scene.set_part("chute", model="BIN-30", category="bin")
    # A fence around the cell — panels of `fence_pitch` along each side, a
    # post at every corner and between panels, the door on the south side —
    # generated by `bt.parts`: every panel and post is an obstacle under
    # `fence/`, and the parts on the group carry the counts.
    bt.parts.fence(
        scene, "fence", path=[(-1.2, -0.6), (1.2, -0.6), (1.2, 1.0), (-1.2, 1.0)],
        height=1.8, panel_pitch=fence_pitch, door=(0, 1), door_model="ST20 door",
        manufacturer="TROAX", model=f"ST20 {fence_pitch:.1f}m", post_model="ST20 post", mass_kg=12,
    )
    # Equipment identity: the arm, the belt, the eye, the controller.
    scene.set_part("simple_arm", manufacturer="ACME", model="SA-6", mass_kg=28)
    scene.set_part("conv", manufacturer="MISUMI", model="GVL-900-200", mass_kg=32)
    scene.set_part("part_at_pick", manufacturer="KEYENCE", model="PZ-G61N")
    scene.set_part("UR", manufacturer="Universal Robots", model="CB3 control box")


def build() -> bt.Scene:
    scene = pick.build_cell()
    pick.author_sequence(scene)
    pick.wire_cell(scene)
    furnish(scene)
    # The FAT row "beam broken" — a stuck sensor is a scenario, and it
    # cannot complete: the report's scenario table shows the stall.
    scene.add_scenario("beam_stuck", faults=[bt.io.stuck("part_at_pick", False)])
    return scene


def deliver(scene: bt.Scene, out: Path) -> bt.CellReport:
    """Writes the document set into `out` and returns the report."""
    out.mkdir(parents=True, exist_ok=True)
    runs = scene.simulate_scenarios(["pick"], max_duration=30.0)
    baseline = runs["baseline"]

    files: list[Path] = []

    def write(name: str, fn) -> Path:
        path = out / name
        fn(path)
        files.append(path)
        return path

    write("cell.botrail", scene.save_project)                       # the portable project
    write("cell.py", lambda p: p.write_text(scene.generate_python()))  # the same cell as code
    write("cell_bom.csv", scene.export_bom)                         # bill of materials
    write("cell_bom.md", scene.export_bom)
    write("cell_io.csv", scene.export_io_list)                      # I/O list for the electrical drawing
    write("cell_topology.mmd", scene.export_topology)               # controller topology
    write("cell.plcopen.xml", lambda p: scene.export_plcopen(p, name="pick cell"))  # the logic, for the PLC IDE
    write("cell_interlocks.md", scene.export_interlocks)               # every output against the condition that admits it
    write("cell_layout.svg", lambda p: scene.export_layout(p, scale=200, title="pick cell"))  # plan view for the review
    write("cell_layout.dxf", lambda p: scene.export_layout(p, title="pick cell"))  # plan view for the 2D CAD
    write("cell_cycle.usda", lambda p: baseline.export_usd(p, fps=30.0))  # the baked cycle
    write("pick_cell.script", runs.export_script)                   # the controller program, both arms

    report = scene.cell_report(
        {"baseline": baseline, "ng_part": runs["ng_part"]},
        scenarios=runs,
        deliverables=files,
        title="pick cell",
    )
    report.save(out / "cell_report.md")
    report.save(out / "cell_report.json")
    return report


def main() -> None:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("deliverables")
    scene = build()
    report = deliver(scene, out)
    print(report.to_markdown())
    print(f"wrote the document set to {out}/ ({len(report.deliverables)} files hashed in the report)")


if __name__ == "__main__":
    main()
