"""botrail: ROS-free robot motion authoring with a web-based 3D studio."""

from . import catalog, gait, io, mounting, paint, parts, select, seq, study, tending, toolpath, tools, trace
from ._core import (
    Bom,
    CellReport,
    InterlockTable,
    Clearance,
    FeedReport,
    FilmCoat,
    Group,
    IkResult,
    IoFinding,
    IoMap,
    IoPoint,
    IoReport,
    PaintReport,
    Robot,
    Scene,
    SequenceTimeline,
    SignalTrack,
    Span,
    StockCarve,
    StudioServer,
    ToolpathReport,
    Trajectory,
    __version__,
    catalog_package,
    project_schema,
)
from .gait import Gait
from ._launcher import studio
from .deliverables import export_cell
from .study import optimize, sweep

__all__ = [
    "mounting",
    "export_cell",
    "Bom",
    "CellReport",
    "InterlockTable",
    "Clearance",
    "FeedReport",
    "FilmCoat",
    "Gait",
    "Group",
    "IkResult",
    "IoFinding",
    "IoMap",
    "IoPoint",
    "IoReport",
    "PaintReport",
    "Robot",
    "Scene",
    "SequenceTimeline",
    "SignalTrack",
    "Span",
    "StockCarve",
    "StudioServer",
    "ToolpathReport",
    "Trajectory",
    "catalog_package",
    "project_schema",
    "catalog",
    "gait",
    "io",
    "paint",
    "parts",
    "select",
    "seq",
    "studio",
    "study",
    "sweep",
    "optimize",
    "tending",
    "toolpath",
    "tools",
    "trace",
    "__version__",
]
