"""botrail: ROS-free robot motion authoring with a web-based 3D studio."""

from . import io, paint, parts, seq, study, toolpath, trace
from ._core import (
    Bom,
    CellReport,
    Clearance,
    FeedReport,
    FilmCoat,
    IkResult,
    IoFinding,
    IoMap,
    IoPoint,
    IoReport,
    PaintReport,
    Robot,
    Scene,
    SequenceTimeline,
    SignalTrack,
    Span,
    StockCarve,
    StudioServer,
    ToolpathReport,
    Trajectory,
    __version__,
    catalog_package,
    project_schema,
)
from ._launcher import studio
from .study import optimize, sweep

__all__ = [
    "Bom",
    "CellReport",
    "Clearance",
    "FeedReport",
    "FilmCoat",
    "IkResult",
    "IoFinding",
    "IoMap",
    "IoPoint",
    "IoReport",
    "PaintReport",
    "Robot",
    "Scene",
    "SequenceTimeline",
    "SignalTrack",
    "Span",
    "StockCarve",
    "StudioServer",
    "ToolpathReport",
    "Trajectory",
    "catalog_package",
    "project_schema",
    "io",
    "paint",
    "parts",
    "seq",
    "studio",
    "study",
    "sweep",
    "optimize",
    "toolpath",
    "trace",
    "__version__",
]
