from pathlib import Path
from typing import Optional, Union

__version__: str

class IkResult:
    @property
    def q(self) -> list[float]: ...
    @property
    def converged(self) -> bool: ...
    @property
    def pos_error(self) -> float: ...
    @property
    def rot_error(self) -> float: ...
    @property
    def iters(self) -> int: ...

class Robot:
    @staticmethod
    def from_urdf(path: Union[str, Path]) -> "Robot": ...
    @staticmethod
    def from_urdf_string(xml: str) -> "Robot": ...
    @staticmethod
    def from_xacro(path: Union[str, Path]) -> "Robot": ...
    @property
    def name(self) -> str: ...
    @property
    def dof(self) -> int: ...
    @property
    def joint_names(self) -> list[str]: ...
    @property
    def joint_limits(self) -> list[Optional[tuple[float, float]]]: ...
    @property
    def link_names(self) -> list[str]: ...
    @property
    def tcp_link(self) -> str: ...
    def ik(
        self,
        position: tuple[float, float, float],
        quaternion: Optional[tuple[float, float, float, float]] = None,
        link: Optional[str] = None,
        seed: Optional[list[float]] = None,
        max_iters: int = 100,
    ) -> IkResult: ...

class Scene:
    def __init__(self, robot: Robot) -> None: ...
    @property
    def robot(self) -> Robot: ...
    @property
    def joint_positions(self) -> list[float]: ...
    def set_joint_positions(self, positions: list[float]) -> None: ...
    def link_pose(
        self, link_name: str
    ) -> tuple[tuple[float, float, float], tuple[float, float, float, float]]: ...
    def set_tcp_target(
        self,
        position: tuple[float, float, float],
        quaternion: Optional[tuple[float, float, float, float]] = None,
        link: Optional[str] = None,
        max_iters: int = 100,
    ) -> IkResult: ...
    def add_box(
        self,
        name: str,
        size: tuple[float, float, float],
        position: tuple[float, float, float],
        quaternion: Optional[tuple[float, float, float, float]] = None,
    ) -> str: ...
    def add_sphere(
        self,
        name: str,
        radius: float,
        position: tuple[float, float, float],
        quaternion: Optional[tuple[float, float, float, float]] = None,
    ) -> str: ...
    def add_cylinder(
        self,
        name: str,
        radius: float,
        length: float,
        position: tuple[float, float, float],
        quaternion: Optional[tuple[float, float, float, float]] = None,
    ) -> str: ...
    def remove_obstacle(self, name: str) -> None: ...
    def set_obstacle_pose(
        self,
        name: str,
        position: tuple[float, float, float],
        quaternion: Optional[tuple[float, float, float, float]] = None,
    ) -> None: ...
    @property
    def obstacle_names(self) -> list[str]: ...
    def check_collisions(
        self,
    ) -> list[tuple[tuple[str, str], tuple[str, str]]]: ...
    def in_collision(self) -> bool: ...
    def min_obstacle_distance(self) -> Optional[float]: ...
    @property
    def collision_warnings(self) -> list[str]: ...

class StudioServer:
    @property
    def url(self) -> str: ...
    def stop(self) -> None: ...

def serve_studio(
    scene: Scene, studio_dir: str, host: str = "127.0.0.1", port: int = 0
) -> StudioServer: ...
