// Wire protocol types, generated from the Rust source of truth
// (crates/botrail-scene/src/wire.rs) by ts-rs.
//
// Do NOT edit the files in ./generated by hand. After changing the Rust
// wire types, regenerate them with: scripts/gen_protocol.sh

export type { PoseMsg } from "./generated/PoseMsg";
export type { GeometryMsg } from "./generated/GeometryMsg";
export type { MaterialMsg } from "./generated/MaterialMsg";
export type { VisualMsg } from "./generated/VisualMsg";
export type { LinkMsg } from "./generated/LinkMsg";
export type { JointTypeMsg } from "./generated/JointTypeMsg";
export type { IkStatusMsg } from "./generated/IkStatusMsg";
export type { ObstacleMsg } from "./generated/ObstacleMsg";
export type { AttachmentMsg } from "./generated/AttachmentMsg";
export type { ObjectTrackMsg } from "./generated/ObjectTrackMsg";
export type { FrameMsg } from "./generated/FrameMsg";
export type { UsdAssetMsg } from "./generated/UsdAssetMsg";
export type { ColliderRefMsg } from "./generated/ColliderRefMsg";
export type { CollisionPairMsg } from "./generated/CollisionPairMsg";
export type { TrajectoryMsg } from "./generated/TrajectoryMsg";
export type { PlanStatsMsg } from "./generated/PlanStatsMsg";
export type { ConstraintMsg } from "./generated/ConstraintMsg";
export type { SegmentKindMsg } from "./generated/SegmentKindMsg";
export type { SegmentMsg } from "./generated/SegmentMsg";
export type { MotionMsg } from "./generated/MotionMsg";
export type { SequenceMsg } from "./generated/SequenceMsg";
export type { StepMsg } from "./generated/StepMsg";
export type { SelectArmMsg } from "./generated/SelectArmMsg";
export type { ActionMsg } from "./generated/ActionMsg";
export type { ConditionMsg } from "./generated/ConditionMsg";
export type { RampTargetMsg } from "./generated/RampTargetMsg";
export type { SignalDefMsg } from "./generated/SignalDefMsg";
export type { StepSpanMsg } from "./generated/StepSpanMsg";
export type { SignalTrackMsg } from "./generated/SignalTrackMsg";
export type { TimelineMsg } from "./generated/TimelineMsg";
export type { SensorMsg } from "./generated/SensorMsg";
export type { SensorKindMsg } from "./generated/SensorKindMsg";
export type { SensorWatchMsg } from "./generated/SensorWatchMsg";
export type { DeviceMsg } from "./generated/DeviceMsg";
export type { DeviceKindMsg } from "./generated/DeviceKindMsg";
export type { DeviceCommandMsg } from "./generated/DeviceCommandMsg";
export type { FlashMsg } from "./generated/FlashMsg";
export type { VehiclePathMsg } from "./generated/VehiclePathMsg";
export type { VehicleStationMsg } from "./generated/VehicleStationMsg";
export type { VehicleTrayMsg } from "./generated/VehicleTrayMsg";
export type { JointMsg } from "./generated/JointMsg";
export type { JointMimicMsg } from "./generated/JointMimicMsg";
export type { RobotDescMsg } from "./generated/RobotDescMsg";
export type { RobotStateMsg } from "./generated/RobotStateMsg";
export type { RobotTimelineMsg } from "./generated/RobotTimelineMsg";
export type { SceneDescriptionMsg } from "./generated/SceneDescriptionMsg";
export type { ServerMessage } from "./generated/ServerMessage";
export type { ClientMessage } from "./generated/ClientMessage";
