// Wire protocol types, generated from the Rust source of truth
// (crates/botrail-scene/src/wire.rs) by ts-rs.
//
// Do NOT edit the files in ./generated by hand. After changing the Rust
// wire types, regenerate them with: scripts/gen_protocol.sh

export type { PoseMsg } from "./generated/PoseMsg";
export type { GeometryMsg } from "./generated/GeometryMsg";
export type { VisualMsg } from "./generated/VisualMsg";
export type { LinkMsg } from "./generated/LinkMsg";
export type { JointTypeMsg } from "./generated/JointTypeMsg";
export type { IkStatusMsg } from "./generated/IkStatusMsg";
export type { ObstacleMsg } from "./generated/ObstacleMsg";
export type { AttachmentMsg } from "./generated/AttachmentMsg";
export type { ObjectTrackMsg } from "./generated/ObjectTrackMsg";
export type { FrameMsg } from "./generated/FrameMsg";
export type { UsdAssetMsg } from "./generated/UsdAssetMsg";
export type { ColliderRefMsg } from "./generated/ColliderRefMsg";
export type { CollisionPairMsg } from "./generated/CollisionPairMsg";
export type { TrajectoryMsg } from "./generated/TrajectoryMsg";
export type { PlanStatsMsg } from "./generated/PlanStatsMsg";
export type { ConstraintMsg } from "./generated/ConstraintMsg";
export type { SegmentKindMsg } from "./generated/SegmentKindMsg";
export type { SegmentMsg } from "./generated/SegmentMsg";
export type { MotionMsg } from "./generated/MotionMsg";
export type { JointMsg } from "./generated/JointMsg";
export type { SceneDescriptionMsg } from "./generated/SceneDescriptionMsg";
export type { ServerMessage } from "./generated/ServerMessage";
export type { ClientMessage } from "./generated/ClientMessage";
