//! URScript backend (Universal Robots, CB-series and e-Series).
//!
//! Emits a `def <name>(): … end` program of `movej`/`movel` commands.
//! URScript units already match the IR (rad, m, s; blend radius `r` in m),
//! and both movej and movel accept joint-valued targets (movel computes
//! the pose via forward kinematics on the controller), so no conversion
//! beyond formatting is needed. `a`/`v` on movej bound the leading axis;
//! on movel they bound the TCP.

use crate::{fmt_num, Command, DigitalTest, ExportError, Program, ScriptBackend};

/// UR arms are 6-axis; movej/movel targets are fixed-length vectors.
const UR_DOF: usize = 6;

pub struct UrScript;

impl ScriptBackend for UrScript {
    fn dialect(&self) -> &'static str {
        "urscript"
    }

    fn file_extension(&self) -> &'static str {
        "script"
    }

    fn emit(&self, program: &Program) -> Result<String, ExportError> {
        if program.dof() != UR_DOF {
            return Err(ExportError::UnsupportedDof {
                dialect: "urscript",
                expected: UR_DOF,
                got: program.dof(),
            });
        }
        let mut out = format!("def {}():\n", sanitize_name(&program.name));
        out.push_str("  # Generated by botrail (units: rad, m, s)\n");
        out.push_str(&format!("  # joints: {}\n", program.joint_names.join(", ")));
        let mut index = 0usize;
        emit_commands(&mut out, &program.commands, 1, &mut index)?;
        out.push_str("end\n");
        Ok(out)
    }
}

/// Emits a command list at `depth` (two spaces per level). `index` runs
/// across the whole program, nesting included, so a dof error names the
/// offending command.
fn emit_commands(
    out: &mut String,
    commands: &[Command],
    depth: usize,
    index: &mut usize,
) -> Result<(), ExportError> {
    let pad = "  ".repeat(depth);
    for command in commands {
        *index += 1;
        match command {
            Command::MoveJoint {
                q,
                velocity,
                acceleration,
                blend,
            } => emit_move(
                out,
                &pad,
                "movej",
                q,
                *velocity,
                *acceleration,
                *blend,
                *index,
            )?,
            Command::MoveLinear {
                q,
                velocity,
                acceleration,
                blend,
            } => emit_move(
                out,
                &pad,
                "movel",
                q,
                *velocity,
                *acceleration,
                *blend,
                *index,
            )?,
            Command::SetDigitalOut { port, value } => {
                out.push_str(&format!(
                    "{pad}set_standard_digital_out({port}, {})\n",
                    pybool(*value)
                ));
            }
            // A level wait: spin on the contact, yielding one control
            // cycle per test (sync() is URScript's cooperative yield).
            Command::WaitDigitalIn { port, value } => {
                let test = if *value {
                    format!("not get_standard_digital_in({port})")
                } else {
                    format!("get_standard_digital_in({port})")
                };
                out.push_str(&format!("{pad}while ({test}):\n{pad}  sync()\n{pad}end\n"));
            }
            Command::Sleep { seconds } => {
                out.push_str(&format!("{pad}sleep({})\n", fmt_num(*seconds)));
            }
            Command::WaitTest { test } => {
                out.push_str(&format!(
                    "{pad}while (not {}):\n{pad}  sync()\n{pad}end\n",
                    test_expr(test)
                ));
            }
            Command::Comment { text } => {
                // Newlines would let a comment smuggle statements in.
                let text = text.replace(['\n', '\r'], " ");
                out.push_str(&format!("{pad}# {text}\n"));
            }
            Command::Select { arms } => {
                if arms.is_empty() {
                    continue;
                }
                // Wait until some arm's guard holds — unless one is
                // vacuously true, in which case the if-chain resolves
                // immediately anyway.
                let vacuous = arms
                    .iter()
                    .any(|arm| matches!(arm.test, DigitalTest::Always));
                if !vacuous {
                    let any = arms
                        .iter()
                        .map(|arm| test_expr(&arm.test))
                        .collect::<Vec<_>>()
                        .join(" or ");
                    out.push_str(&format!(
                        "{pad}while (not ({any})):\n{pad}  sync()\n{pad}end\n"
                    ));
                }
                for (j, arm) in arms.iter().enumerate() {
                    let keyword = if j == 0 { "if" } else { "elif" };
                    out.push_str(&format!("{pad}{keyword} ({}):\n", test_expr(&arm.test)));
                    if arm.body.is_empty() {
                        // An empty block is a syntax error; a yield is the
                        // honest no-op.
                        out.push_str(&format!("{pad}  sync()\n"));
                    } else {
                        emit_commands(out, &arm.body, depth + 1, index)?;
                    }
                }
                out.push_str(&format!("{pad}end\n"));
            }
        }
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn emit_move(
    out: &mut String,
    pad: &str,
    op: &str,
    q: &[f64],
    velocity: f64,
    acceleration: f64,
    blend: f64,
    index: usize,
) -> Result<(), ExportError> {
    if q.len() != UR_DOF {
        return Err(ExportError::WrongDof {
            index: index - 1,
            expected: UR_DOF,
            got: q.len(),
        });
    }
    let joints = q.iter().map(|x| fmt_num(*x)).collect::<Vec<_>>().join(", ");
    out.push_str(&format!(
        "{pad}{op}([{joints}], a={}, v={}, r={})\n",
        fmt_num(acceleration),
        fmt_num(velocity),
        fmt_num(blend),
    ));
    Ok(())
}

/// A [`DigitalTest`] as a URScript boolean expression.
fn test_expr(test: &DigitalTest) -> String {
    match test {
        DigitalTest::Input { port, value } => {
            if *value {
                format!("get_standard_digital_in({port})")
            } else {
                format!("not get_standard_digital_in({port})")
            }
        }
        DigitalTest::Always => "True".to_string(),
        DigitalTest::AllOf(tests) => group(tests, " and "),
        DigitalTest::AnyOf(tests) => group(tests, " or "),
    }
}

fn group(tests: &[DigitalTest], joiner: &str) -> String {
    if tests.is_empty() {
        return "True".to_string();
    }
    let parts: Vec<String> = tests.iter().map(test_expr).collect();
    format!("({})", parts.join(joiner))
}

fn pybool(value: bool) -> &'static str {
    if value {
        "True"
    } else {
        "False"
    }
}

/// URScript identifiers: ASCII letters/digits/underscore, starting with a
/// letter. Anything else is replaced or prefixed away.
fn sanitize_name(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    match cleaned.chars().next() {
        Some(c) if c.is_ascii_alphabetic() => cleaned,
        Some(_) => format!("botrail_{cleaned}"),
        None => "botrail_program".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{build_program, PathKind, PathSegment, ProgramOptions};

    fn ur_names() -> Vec<String> {
        [
            "shoulder_pan",
            "shoulder_lift",
            "elbow",
            "wrist_1",
            "wrist_2",
            "wrist_3",
        ]
        .map(String::from)
        .to_vec()
    }

    #[test]
    fn golden_program() {
        let segments = vec![
            PathSegment {
                kind: PathKind::Joint,
                waypoints: vec![
                    vec![0.0; 6],
                    vec![0.3, 0.2, -0.25, 0.1, 0.0, 0.0],
                    vec![0.6, 0.4, -0.5, 0.2, 0.0, 0.0],
                ],
            },
            PathSegment {
                kind: PathKind::Linear,
                waypoints: vec![
                    vec![0.6, 0.4, -0.5, 0.2, 0.0, 0.0],
                    vec![0.575, 0.425, -0.525, 0.2, 0.0, 0.0],
                    vec![0.55, 0.45, -0.55, 0.2, 0.0, 0.0],
                ],
            },
        ];
        let options = ProgramOptions {
            blend_radius: 0.025,
            ..ProgramOptions::default()
        };
        let program = build_program(
            "pick",
            &ur_names(),
            &segments,
            &[2.0, 2.0, 2.5, 3.0, 3.0, 3.0],
            &[4.0, 4.0, 5.0, 6.0, 6.0, 6.0],
            &options,
        )
        .unwrap();
        let script = UrScript.emit(&program).unwrap();
        let expected = "\
def pick():
  # Generated by botrail (units: rad, m, s)
  # joints: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
  movej([0, 0, 0, 0, 0, 0], a=4, v=2, r=0)
  movej([0.3, 0.2, -0.25, 0.1, 0, 0], a=4, v=2, r=0.025)
  movej([0.6, 0.4, -0.5, 0.2, 0, 0], a=4, v=2, r=0)
  movel([0.55, 0.45, -0.55, 0.2, 0, 0], a=1.2, v=0.25, r=0)
end
";
        assert_eq!(script, expected);
    }

    #[test]
    fn io_commands_render() {
        let program = Program {
            name: "cell".into(),
            joint_names: ur_names(),
            commands: vec![
                Command::Comment {
                    text: "step 1: wait\nfor part".into(),
                },
                Command::WaitDigitalIn {
                    port: 3,
                    value: true,
                },
                Command::SetDigitalOut {
                    port: 0,
                    value: false,
                },
                Command::Sleep { seconds: 0.4 },
                Command::WaitDigitalIn {
                    port: 5,
                    value: false,
                },
                Command::SetDigitalOut {
                    port: 1,
                    value: true,
                },
            ],
        };
        let script = UrScript.emit(&program).unwrap();
        let expected = "\
def cell():
  # Generated by botrail (units: rad, m, s)
  # joints: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
  # step 1: wait for part
  while (not get_standard_digital_in(3)):
    sync()
  end
  set_standard_digital_out(0, False)
  sleep(0.4)
  while (get_standard_digital_in(5)):
    sync()
  end
  set_standard_digital_out(1, True)
end
";
        assert_eq!(script, expected);
    }

    #[test]
    fn select_renders_wait_any_and_if_chain() {
        let arm = |port: u32, body: Vec<Command>| crate::SelectArm {
            test: DigitalTest::Input { port, value: true },
            body,
        };
        let program = Program {
            name: "gate".into(),
            joint_names: ur_names(),
            commands: vec![Command::Select {
                arms: vec![
                    arm(
                        2,
                        vec![
                            Command::SetDigitalOut {
                                port: 0,
                                value: true,
                            },
                            Command::MoveJoint {
                                q: vec![0.0; 6],
                                velocity: 1.0,
                                acceleration: 2.0,
                                blend: 0.0,
                            },
                        ],
                    ),
                    // An empty arm still needs a statement.
                    arm(3, vec![]),
                ],
            }],
        };
        let script = UrScript.emit(&program).unwrap();
        let expected = "\
def gate():
  # Generated by botrail (units: rad, m, s)
  # joints: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
  while (not (get_standard_digital_in(2) or get_standard_digital_in(3))):
    sync()
  end
  if (get_standard_digital_in(2)):
    set_standard_digital_out(0, True)
    movej([0, 0, 0, 0, 0, 0], a=2, v=1, r=0)
  elif (get_standard_digital_in(3)):
    sync()
  end
end
";
        assert_eq!(script, expected);
    }

    #[test]
    fn compound_tests_render_as_boolean_expressions() {
        let test = DigitalTest::AnyOf(vec![
            DigitalTest::AllOf(vec![
                DigitalTest::Input {
                    port: 0,
                    value: true,
                },
                DigitalTest::Input {
                    port: 1,
                    value: false,
                },
            ]),
            DigitalTest::Always,
        ]);
        assert_eq!(
            test_expr(&test),
            "((get_standard_digital_in(0) and not get_standard_digital_in(1)) or True)"
        );
    }

    #[test]
    fn non_six_axis_is_rejected() {
        let program = Program {
            name: "p".into(),
            joint_names: vec!["a".into(), "b".into()],
            commands: vec![Command::MoveJoint {
                q: vec![0.0, 0.0],
                velocity: 1.0,
                acceleration: 1.0,
                blend: 0.0,
            }],
        };
        assert!(matches!(
            UrScript.emit(&program),
            Err(ExportError::UnsupportedDof {
                dialect: "urscript",
                expected: 6,
                ..
            })
        ));
    }

    #[test]
    fn names_are_sanitized() {
        assert_eq!(sanitize_name("pick"), "pick");
        assert_eq!(sanitize_name("pick&place 1"), "pick_place_1");
        assert_eq!(sanitize_name("1st"), "botrail_1st");
        assert_eq!(sanitize_name(""), "botrail_program");
        assert_eq!(sanitize_name("日本語"), "botrail____");
    }
}
