//! URScript backend (Universal Robots, CB-series and e-Series).
//!
//! Emits a `def <name>(): … end` program of `movej`/`movel` commands.
//! URScript units already match the IR (rad, m, s; blend radius `r` in m),
//! and both movej and movel accept joint-valued targets (movel computes
//! the pose via forward kinematics on the controller), so no conversion
//! beyond formatting is needed. `a`/`v` on movej bound the leading axis;
//! on movel they bound the TCP.

use crate::{fmt_num, Command, ExportError, Program, ScriptBackend};

/// UR arms are 6-axis; movej/movel targets are fixed-length vectors.
const UR_DOF: usize = 6;

pub struct UrScript;

impl ScriptBackend for UrScript {
    fn dialect(&self) -> &'static str {
        "urscript"
    }

    fn file_extension(&self) -> &'static str {
        "script"
    }

    fn emit(&self, program: &Program) -> Result<String, ExportError> {
        if program.dof() != UR_DOF {
            return Err(ExportError::UnsupportedDof {
                dialect: "urscript",
                expected: UR_DOF,
                got: program.dof(),
            });
        }
        let mut out = format!("def {}():\n", sanitize_name(&program.name));
        out.push_str("  # Generated by botrail (units: rad, m, s)\n");
        out.push_str(&format!("  # joints: {}\n", program.joint_names.join(", ")));
        for (index, command) in program.commands.iter().enumerate() {
            let (op, q, velocity, acceleration, blend) = match command {
                Command::MoveJoint {
                    q,
                    velocity,
                    acceleration,
                    blend,
                } => ("movej", q, velocity, acceleration, blend),
                Command::MoveLinear {
                    q,
                    velocity,
                    acceleration,
                    blend,
                } => ("movel", q, velocity, acceleration, blend),
                Command::SetDigitalOut { port, value } => {
                    out.push_str(&format!(
                        "  set_standard_digital_out({port}, {})\n",
                        pybool(*value)
                    ));
                    continue;
                }
                // A level wait: spin on the contact, yielding one control
                // cycle per test (sync() is URScript's cooperative yield).
                Command::WaitDigitalIn { port, value } => {
                    let test = if *value {
                        format!("not get_standard_digital_in({port})")
                    } else {
                        format!("get_standard_digital_in({port})")
                    };
                    out.push_str(&format!("  while ({test}):\n    sync()\n  end\n"));
                    continue;
                }
                Command::Sleep { seconds } => {
                    out.push_str(&format!("  sleep({})\n", fmt_num(*seconds)));
                    continue;
                }
                Command::Comment { text } => {
                    // Newlines would let a comment smuggle statements in.
                    let text = text.replace(['\n', '\r'], " ");
                    out.push_str(&format!("  # {text}\n"));
                    continue;
                }
            };
            if q.len() != UR_DOF {
                return Err(ExportError::WrongDof {
                    index,
                    expected: UR_DOF,
                    got: q.len(),
                });
            }
            let joints = q.iter().map(|x| fmt_num(*x)).collect::<Vec<_>>().join(", ");
            out.push_str(&format!(
                "  {op}([{joints}], a={}, v={}, r={})\n",
                fmt_num(*acceleration),
                fmt_num(*velocity),
                fmt_num(*blend),
            ));
        }
        out.push_str("end\n");
        Ok(out)
    }
}

fn pybool(value: bool) -> &'static str {
    if value {
        "True"
    } else {
        "False"
    }
}

/// URScript identifiers: ASCII letters/digits/underscore, starting with a
/// letter. Anything else is replaced or prefixed away.
fn sanitize_name(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    match cleaned.chars().next() {
        Some(c) if c.is_ascii_alphabetic() => cleaned,
        Some(_) => format!("botrail_{cleaned}"),
        None => "botrail_program".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{build_program, PathKind, PathSegment, ProgramOptions};

    fn ur_names() -> Vec<String> {
        [
            "shoulder_pan",
            "shoulder_lift",
            "elbow",
            "wrist_1",
            "wrist_2",
            "wrist_3",
        ]
        .map(String::from)
        .to_vec()
    }

    #[test]
    fn golden_program() {
        let segments = vec![
            PathSegment {
                kind: PathKind::Joint,
                waypoints: vec![
                    vec![0.0; 6],
                    vec![0.3, 0.2, -0.25, 0.1, 0.0, 0.0],
                    vec![0.6, 0.4, -0.5, 0.2, 0.0, 0.0],
                ],
            },
            PathSegment {
                kind: PathKind::Linear,
                waypoints: vec![
                    vec![0.6, 0.4, -0.5, 0.2, 0.0, 0.0],
                    vec![0.575, 0.425, -0.525, 0.2, 0.0, 0.0],
                    vec![0.55, 0.45, -0.55, 0.2, 0.0, 0.0],
                ],
            },
        ];
        let options = ProgramOptions {
            blend_radius: 0.025,
            ..ProgramOptions::default()
        };
        let program = build_program(
            "pick",
            &ur_names(),
            &segments,
            &[2.0, 2.0, 2.5, 3.0, 3.0, 3.0],
            &[4.0, 4.0, 5.0, 6.0, 6.0, 6.0],
            &options,
        )
        .unwrap();
        let script = UrScript.emit(&program).unwrap();
        let expected = "\
def pick():
  # Generated by botrail (units: rad, m, s)
  # joints: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
  movej([0, 0, 0, 0, 0, 0], a=4, v=2, r=0)
  movej([0.3, 0.2, -0.25, 0.1, 0, 0], a=4, v=2, r=0.025)
  movej([0.6, 0.4, -0.5, 0.2, 0, 0], a=4, v=2, r=0)
  movel([0.55, 0.45, -0.55, 0.2, 0, 0], a=1.2, v=0.25, r=0)
end
";
        assert_eq!(script, expected);
    }

    #[test]
    fn io_commands_render() {
        let program = Program {
            name: "cell".into(),
            joint_names: ur_names(),
            commands: vec![
                Command::Comment {
                    text: "step 1: wait\nfor part".into(),
                },
                Command::WaitDigitalIn {
                    port: 3,
                    value: true,
                },
                Command::SetDigitalOut {
                    port: 0,
                    value: false,
                },
                Command::Sleep { seconds: 0.4 },
                Command::WaitDigitalIn {
                    port: 5,
                    value: false,
                },
                Command::SetDigitalOut {
                    port: 1,
                    value: true,
                },
            ],
        };
        let script = UrScript.emit(&program).unwrap();
        let expected = "\
def cell():
  # Generated by botrail (units: rad, m, s)
  # joints: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
  # step 1: wait for part
  while (not get_standard_digital_in(3)):
    sync()
  end
  set_standard_digital_out(0, False)
  sleep(0.4)
  while (get_standard_digital_in(5)):
    sync()
  end
  set_standard_digital_out(1, True)
end
";
        assert_eq!(script, expected);
    }

    #[test]
    fn non_six_axis_is_rejected() {
        let program = Program {
            name: "p".into(),
            joint_names: vec!["a".into(), "b".into()],
            commands: vec![Command::MoveJoint {
                q: vec![0.0, 0.0],
                velocity: 1.0,
                acceleration: 1.0,
                blend: 0.0,
            }],
        };
        assert!(matches!(
            UrScript.emit(&program),
            Err(ExportError::UnsupportedDof {
                dialect: "urscript",
                expected: 6,
                ..
            })
        ));
    }

    #[test]
    fn names_are_sanitized() {
        assert_eq!(sanitize_name("pick"), "pick");
        assert_eq!(sanitize_name("pick&place 1"), "pick_place_1");
        assert_eq!(sanitize_name("1st"), "botrail_1st");
        assert_eq!(sanitize_name(""), "botrail_program");
        assert_eq!(sanitize_name("日本語"), "botrail____");
    }
}
